version: "3"
services:
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "8026:8025"
      - "1026:1025"
  pgdev:
    container_name: teamdream_pgdev
    restart: always
    image: postgres:9.6.8
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: teamdream
      POSTGRES_PASSWORD: teamdream_pw
  pgtest:
    container_name: teamdream_pgtest
    restart: always
    image: postgres:9.6.8
    ports:
      - "5566:5432"
    environment:
      POSTGRES_USER: teamdream_test
      POSTGRES_PASSWORD: teamdream_test_pw
  s3test:
    container_name: teamdream_s3test
    restart: always
    image: minio/minio:RELEASE.2018-12-06T01-27-43Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: s3user
      MINIO_SECRET_KEY: s3user-s3cr3t
    command: server /data
